2022-01-09 18:54:18,065 INFO    MainThread:20984 [internal.py:wandb_internal():90] W&B internal server running at pid: 20984, started at: 2022-01-09 18:54:18.064991
2022-01-09 18:54:18,069 DEBUG   HandlerThread:20984 [handler.py:handle_request():130] handle_request: run_start
2022-01-09 18:54:18,069 INFO    WriterThread:20984 [datastore.py:open_for_write():77] open: /content/tbcnn/wandb/offline-run-20220109_185416-1w8gng5u/run-1w8gng5u.wandb
2022-01-09 18:54:20,798 DEBUG   HandlerThread:20984 [meta.py:__init__():40] meta init
2022-01-09 18:54:20,798 DEBUG   HandlerThread:20984 [meta.py:__init__():54] meta init done
2022-01-09 18:54:20,798 DEBUG   HandlerThread:20984 [meta.py:probe():214] probe
2022-01-09 18:54:20,801 DEBUG   HandlerThread:20984 [meta.py:_setup_git():204] setup git
2022-01-09 18:54:20,826 DEBUG   HandlerThread:20984 [meta.py:_setup_git():211] setup git done
2022-01-09 18:54:20,826 DEBUG   HandlerThread:20984 [meta.py:_save_pip():58] save pip
2022-01-09 18:54:20,827 DEBUG   HandlerThread:20984 [meta.py:_save_pip():72] save pip done
2022-01-09 18:54:20,828 DEBUG   HandlerThread:20984 [meta.py:probe():252] probe done
2022-01-09 18:56:17,000 WARNING MainThread:20984 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-09 18:56:20,013 WARNING MainThread:20984 [internal.py:is_dead():367] Internal process exiting, parent pid 20972 disappeared
2022-01-09 18:56:20,013 ERROR   MainThread:20984 [internal.py:wandb_internal():142] Internal process shutdown.
2022-01-09 18:56:20,111 INFO    SenderThread:20984 [sender.py:finish():1070] shutting down sender
2022-01-09 18:56:20,447 INFO    HandlerThread:20984 [handler.py:finish():731] shutting down handler
2022-01-09 18:56:20,449 INFO    WriterThread:20984 [datastore.py:close():281] close: /content/tbcnn/wandb/offline-run-20220109_185416-1w8gng5u/run-1w8gng5u.wandb
2022-01-09 18:56:20,474 INFO    MainThread:20984 [internal.py:handle_exit():77] Internal process exited
