2022-01-09 18:15:27,449 INFO    MainThread:17560 [wandb_setup.py:_flush():71] setting env: {}
2022-01-09 18:15:27,449 INFO    MainThread:17560 [wandb_init.py:_log_setup():371] Logging user logs to /content/tbcnn/wandb/offline-run-20220109_181527-2jb5g9ld/logs/debug.log
2022-01-09 18:15:27,449 INFO    MainThread:17560 [wandb_init.py:_log_setup():372] Logging internal logs to /content/tbcnn/wandb/offline-run-20220109_181527-2jb5g9ld/logs/debug-internal.log
2022-01-09 18:15:27,449 INFO    MainThread:17560 [wandb_init.py:init():404] calling init triggers
2022-01-09 18:15:27,449 INFO    MainThread:17560 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-09 18:15:27,449 INFO    MainThread:17560 [wandb_init.py:init():460] starting backend
2022-01-09 18:15:27,450 INFO    MainThread:17560 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-09 18:15:27,463 INFO    MainThread:17560 [backend.py:ensure_launched():216] starting backend process...
2022-01-09 18:15:27,471 INFO    MainThread:17560 [backend.py:ensure_launched():222] started backend process with pid: 17570
2022-01-09 18:15:27,473 INFO    MainThread:17560 [wandb_init.py:init():469] backend started and connected
2022-01-09 18:15:27,483 INFO    MainThread:17560 [wandb_init.py:init():533] updated telemetry
2022-01-09 18:15:27,526 INFO    MainThread:17560 [wandb_init.py:init():606] starting run threads in backend
2022-01-09 18:15:31,304 INFO    MainThread:17560 [wandb_run.py:_console_start():1810] atexit reg
2022-01-09 18:15:31,305 INFO    MainThread:17560 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-09 18:15:31,305 INFO    MainThread:17560 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-09 18:15:31,307 INFO    MainThread:17560 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-09 18:15:31,307 INFO    MainThread:17560 [wandb_init.py:init():633] run started, returning control to user process
2022-01-09 18:15:36,410 INFO    MainThread:17560 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-09 18:15:36,411 INFO    MainThread:17560 [wandb_run.py:_restore():1752] restore
2022-01-09 18:15:38,520 INFO    MainThread:17560 [wandb_run.py:_wait_for_finish():1912] got exit ret: 
2022-01-09 18:15:38,622 INFO    MainThread:17560 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
local_info {
}

