2022-01-09 18:14:38,022 INFO    MainThread:17500 [wandb_setup.py:_flush():71] setting env: {}
2022-01-09 18:14:38,022 INFO    MainThread:17500 [wandb_init.py:_log_setup():371] Logging user logs to /content/tbcnn/wandb/offline-run-20220109_181438-1n8t8we8/logs/debug.log
2022-01-09 18:14:38,022 INFO    MainThread:17500 [wandb_init.py:_log_setup():372] Logging internal logs to /content/tbcnn/wandb/offline-run-20220109_181438-1n8t8we8/logs/debug-internal.log
2022-01-09 18:14:38,022 INFO    MainThread:17500 [wandb_init.py:init():404] calling init triggers
2022-01-09 18:14:38,023 INFO    MainThread:17500 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-01-09 18:14:38,023 INFO    MainThread:17500 [wandb_init.py:init():460] starting backend
2022-01-09 18:14:38,023 INFO    MainThread:17500 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-09 18:14:38,040 INFO    MainThread:17500 [backend.py:ensure_launched():216] starting backend process...
2022-01-09 18:14:38,049 INFO    MainThread:17500 [backend.py:ensure_launched():222] started backend process with pid: 17512
2022-01-09 18:14:38,056 INFO    MainThread:17500 [wandb_init.py:init():469] backend started and connected
2022-01-09 18:14:38,060 INFO    MainThread:17500 [wandb_init.py:init():533] updated telemetry
2022-01-09 18:14:38,105 INFO    MainThread:17500 [wandb_init.py:init():606] starting run threads in backend
2022-01-09 18:14:41,897 INFO    MainThread:17500 [wandb_run.py:_console_start():1810] atexit reg
2022-01-09 18:14:41,897 INFO    MainThread:17500 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-09 18:14:41,898 INFO    MainThread:17500 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-09 18:14:41,904 INFO    MainThread:17500 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-09 18:14:41,904 INFO    MainThread:17500 [wandb_init.py:init():633] run started, returning control to user process
2022-01-09 18:14:53,614 INFO    MainThread:17500 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-09 18:14:53,615 INFO    MainThread:17500 [wandb_run.py:_restore():1752] restore
2022-01-09 18:14:55,744 INFO    MainThread:17500 [wandb_run.py:_wait_for_finish():1912] got exit ret: 
2022-01-09 18:14:55,846 INFO    MainThread:17500 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
local_info {
}

